[project]
name = "hardware-software"
version = "1.0.0"
description = "Software para gerenciamento de uma loja de hardware"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymysql>=1.1.1",
    "pyqt6>=6.9.1",
    "python-dotenv>=1.1.0",
    "sqlalchemy>=2.0.41",
]
